---
- hosts: localvms
  become: true
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Pull Linkding Docker image
      docker_image:
        name: sissbruecker/linkding
        source: pull

    - name: Run Linkding container
      docker_container:
        name: linkding
        image: sissbruecker/linkding
        state: started
        ports:
          - "9090:9090"
        # volumes:
        #   - /your/local/data:/etc/linkding/data

    # - name: Copy data to container directory
    #   copy:
    #     src: /path/to/your/data/
    #     dest: /your/local/data/
    #     owner: root
    #     group: root
    #     mode: '0755'    
